const memberData = [
  {
    id: "shopper1",
    type: "admin",
    password: "shop123",
    user_idx: 201,
    name: "김지우",
    phone: "010-1234-5678",
    company: "ABC Corp",
    home: "서울시 강남구",
  },
  {
    id: "shopper2",
    type: "crew",
    password: "sell456",
    user_idx: 202,
    name: "박성훈",
    phone: "010-2345-6789",
    company: "XYZ Inc",
    home: "서울시 서초구",
  },
  {
    id: "admin1",
    type: "crew",
    password: "admin789",
    user_idx: 203,
    name: "김태리",
    phone: "010-3456-7890",
    company: "DEF Ltd",
    home: "서울시 송파구",
  },
  // 추가된 데이터
  {
    id: "crew1",
    type: "crew",
    password: "crew101",
    user_idx: 204,
    name: "이민호",
    phone: "010-4567-8901",
    company: "GHI Group",
    home: "서울시 마포구",
  },
  {
    id: "admin2",
    type: "admin",
    password: "admin202",
    user_idx: 205,
    name: "장예은",
    phone: "010-5678-9012",
    company: "JKL Co.",
    home: "서울시 종로구",
  },
  {
    id: "shopper3",
    type: "crew",
    password: "sell789",
    user_idx: 206,
    name: "최준영",
    phone: "010-6789-0123",
    company: "MNO Enterprises",
    home: "서울시 동작구",
  },
  {
    id: "admin3",
    type: "admin",
    password: "admin303",
    user_idx: 207,
    name: "한수진",
    phone: "010-7890-1234",
    company: "PQR Ltd",
    home: "서울시 성동구",
  },
  {
    id: "crew2",
    type: "crew",
    password: "crew202",
    user_idx: 208,
    name: "오세훈",
    phone: "010-8901-2345",
    company: "STU Corporation",
    home: "서울시 은평구",
  },
  {
    id: "shopper4",
    type: "crew",
    password: "sell456",
    user_idx: 209,
    name: "정수현",
    phone: "010-9012-3456",
    company: "VWX Global",
    home: "서울시 강북구",
  },
  {
    id: "admin4",
    type: "admin",
    password: "admin404",
    user_idx: 210,
    name: "권민지",
    phone: "010-0123-4567",
    company: "YZA Holdings",
    home: "서울시 관악구",
  },
];

export default memberData;
