const scheduleData = {
  "2024-11-20": [
    {
      userIdx: 201,
      start_time: "08:30",
      end_time: "10:00",
      title: "인천 TO 마포",
      attendanc: true,
    },
    {
      userIdx: 202,
      start_time: "11:30",
      end_time: "12:30",
      title: "서울 TO 강남",
      attendanc: false,
    },
    {
      userIdx: 203,
      start_time: "14:00",
      end_time: "15:30",
      title: "부산 TO 대구",
      attendanc: true,
    },
    {
      userIdx: 204,
      start_time: "16:00",
      end_time: "17:45",
      title: "광주 TO 전주",
      attendanc: false,
    },
    {
      userIdx: 205,
      start_time: "18:30",
      end_time: "20:00",
      title: "대전 TO 청주",
      attendanc: true,
    },
  ],
  "2024-11-21": [
    {
      userIdx: 201,
      start_time: "07:15",
      end_time: "09:00",
      title: "인천 TO 송파",
      attendanc: true,
    },
    {
      userIdx: 202,
      start_time: "09:30",
      end_time: "11:00",
      title: "서울 TO 원주",
      attendanc: false,
    },
    {
      userIdx: 203,
      start_time: "12:00",
      end_time: "13:45",
      title: "부산 TO 울산",
      attendanc: true,
    },
    {
      userIdx: 204,
      start_time: "14:30",
      end_time: "16:15",
      title: "광주 TO 나주",
      attendanc: false,
    },
    {
      userIdx: 205,
      start_time: "17:00",
      end_time: "18:45",
      title: "대구 TO 구미",
      attendanc: true,
    },
  ],
  "2024-11-22": [
    {
      userIdx: 201,
      start_time: "06:30",
      end_time: "08:00",
      title: "김포 TO 종로",
      attendanc: true,
    },
    {
      userIdx: 202,
      start_time: "08:30",
      end_time: "10:15",
      title: "서울 TO 용인",
      attendanc: false,
    },
    {
      userIdx: 203,
      start_time: "11:00",
      end_time: "12:45",
      title: "부산 TO 진주",
      attendanc: true,
    },
    {
      userIdx: 204,
      start_time: "13:30",
      end_time: "15:00",
      title: "광주 TO 순천",
      attendanc: false,
    },
    {
      userIdx: 205,
      start_time: "15:30",
      end_time: "17:15",
      title: "대구 TO 포항",
      attendanc: true,
    },
  ],
  "2024-11-23": [
    {
      userIdx: 201,
      start_time: "07:10",
      end_time: "08:30",
      title: "대구 TO 동대구",
      attendanc: true,
    },
    {
      userIdx: 202,
      start_time: "09:00",
      end_time: "10:30",
      title: "서울 TO 남양주",
      attendanc: false,
    },
    {
      userIdx: 203,
      start_time: "11:00",
      end_time: "12:30",
      title: "인천 TO 강화",
      attendanc: true,
    },
    {
      userIdx: 204,
      start_time: "13:00",
      end_time: "14:30",
      title: "부산 TO 해운대",
      attendanc: false,
    },
    {
      userIdx: 205,
      start_time: "15:00",
      end_time: "16:45",
      title: "광주 TO 전남대",
      attendanc: true,
    },
  ],
  "2024-11-24": [
    {
      userIdx: 201,
      start_time: "06:45",
      end_time: "08:15",
      title: "서울 TO 평택",
      attendanc: true,
    },
    {
      userIdx: 202,
      start_time: "09:30",
      end_time: "11:00",
      title: "부산 TO 거제",
      attendanc: false,
    },
    {
      userIdx: 203,
      start_time: "12:15",
      end_time: "13:45",
      title: "광주 TO 담양",
      attendanc: true,
    },
    {
      userIdx: 204,
      start_time: "14:30",
      end_time: "16:00",
      title: "대구 TO 상주",
      attendanc: false,
    },
    {
      userIdx: 205,
      start_time: "16:45",
      end_time: "18:15",
      title: "인천 TO 춘천",
      attendanc: true,
    },
  ],
};
export default scheduleData;
